# Dependabot configuration for automated dependency updates
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kebrahimpour"
    assignees:
      - "kebrahimpour"
    commit-message:
      prefix: "ci"
      include: "scope"
  
  # Python dependencies (via pip/uv)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kebrahimpour"
    assignees:
      - "kebrahimpour"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group minor and patch updates together
    groups:
      python-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
